# Generated by Django 4.0.5 on 2022-06-17 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='domain',
            field=models.CharField(choices=[('SCIENCE', 'SCIENCE'), ('ART', 'ART'), ('OTHERS', 'OTHERS'), ('NONE', 'NONE')], default='NONE', max_length=10),
        ),
    ]
