# Generated by Django 4.0.5 on 2022-06-18 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_question_domain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='domain',
            field=models.CharField(choices=[('OTHERS', 'OTHERS'), ('MATHEMATICS', 'MATHEMATICS'), ('ENGLISH STUDIES', 'ENGLISH STUDIES'), ('GOEGRAPHY', 'GOEGRAPHY'), ('CHEMISTRY', 'CHEMISTRY'), ('PHYSICS', 'PHYSICS'), ('HISTORY', 'HISTORY'), ('COMPUTER STUDIES', 'COMPUTER STUDIES'), ('CHRISTIAN RELIGIOUS STUDIES', 'CHRISTIAN RELIGIOUS STUDIES'), ('FURTHER MATHEMATICS', 'FURTHER MATHEMATICS'), ('ECONOMICS', 'ECONOMICS'), ('BIOLOGY', 'BIOLOGY'), ('NONE', 'NONE')], default='NONE', max_length=28),
        ),
    ]
